### ISSUE TITLE
Failed to format XLSX SaleLine data

### ISSUE THREAD

**Issue by JustApu** [beckf/lightspeed-vc-connector#72]
[lsvc-debug.txt](https://github.com/beckf/lightspeed-vc-connector/files/10242310/lsvc-debug.txt)
I have "enable debugging" checked in Settings but the log doesn't give me much info. Anything I can do to help narrowdown the cause? (I do have Excel installed; not sure if that is a requirement but it is there.)

P.S. Also curious about the decision to export to XLSX since the Veracross Importer wants CSV files.

Thanks, Forest.

**Comment by beckf** [comment]
Hey @JustApu - Originally when I was supporting Windows and Mac, I moved to Excel as the native format because of an issue with linebreaks between different platforms.  I could either see if compiling for Mac is working better now with pyinstaller, continuing with Excel; or switch to CSV and only support Win where pyinstaller works well. 

Have you tried running from source? I could send instructions for getting that running.  You just need to install Python and setup a virtualenv with all requirements.

I could look at adding some additional debugging as well.

**Comment by beckf** [comment]
This one should dump more debug info.
https://github.com/beckf/lightspeed-vc-connector/releases/tag/v1.53

**Comment by beckf** [comment]
Just checking in.  Did the updated version provide any help?

**Comment by JustApu** [comment]
Haven't had a chance to try. Probably Friday Dec. 30, 2022.

**Comment by JustApu** [comment]
1.53b worked - thanks!

**Comment by beckf** [comment]
Ok. I guess it didn't fail to kick out more debug. We can watch to make sure it doesn't become a pattern.
